import { ref } from "vue";
import { defineStore } from "pinia";
import peaches from "@/assets/images/peaches.jpg";

export const useMySongListStore = defineStore("mySongList", () => {
  const mySongList = ref<AlbumData[]>([
    {
      id: 1,
      albumName: "8月",
      imgUrl:
        "https://gimg3.baidu.com/yule/src=http%3A%2F%2Fgips2.baidu.com%2Fit%2Fu%3D3536853671%2C1271261279%26fm%3D3007%26app%3D3007%26f%3DPNG%3Fw%3D500%26h%3D500&refer=http%3A%2F%2Fwww.baidu.com&app=2019&size=w931&n=0&g=0n&q=75&fmt=auto?sec=1728925200&t=04a34a52a220ea7c132cd23b78ad04dc",
      songList: [
        {
          id: 1,
          songName: "夏夜最后的烟火",
          singerName: "颜人中",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏夜最后的烟火",
          imgUrl:
            "https://gimg3.baidu.com/yule/src=http%3A%2F%2Fgips2.baidu.com%2Fit%2Fu%3D3536853671%2C1271261279%26fm%3D3007%26app%3D3007%26f%3DPNG%3Fw%3D500%26h%3D500&refer=http%3A%2F%2Fwww.baidu.com&app=2019&size=w931&n=0&g=0n&q=75&fmt=auto?sec=1728925200&t=04a34a52a220ea7c132cd23b78ad04dc",
          duration: 180,
        },
        {
          id: 2,
          songName: "我只能离开",
          singerName: "颜人中",
          songUrl: "test1.ogg",
          isLike: false,
          albumName: "夏夜最后的烟火",
          imgUrl: peaches,
          duration: 180,
        },
        {
          id: 3,
          songName: "慢慢",
          singerName: "颜人中",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏夜最后的烟火",
          imgUrl: peaches,
          duration: 180,
        },
        {
          id: 4,
          songName: "Peaches",
          singerName: "Justin Bieber",
          songUrl: "test1.ogg",
          isLike: false,
          albumName: "夏夜最后的烟火",
          imgUrl: peaches,
          duration: 180,
        },
      ],
    },
    {
      id: 2,
      albumName: "情歌",
      imgUrl: peaches,
      songList: [
        {
          id: 21,
          songName: "太阳",
          singerName: "刘鹏",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏夜最后的烟火",
          imgUrl: peaches,
          duration: 180,
        },
        {
          id: 22,
          songName: "我会等",
          singerName: "承恒",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏夜最后的烟火",
          imgUrl: peaches,
          duration: 180,
        },
        {
          id: 23,
          songName: "可能",
          singerName: "程响",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏夜最后的烟火",
          imgUrl: peaches,
          duration: 180,
        },
        {
          id: 24,
          songName: "一个傻子",
          singerName: "杨博然",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏夜最后的烟火",
          imgUrl: peaches,
          duration: 180,
        },
      ],
    },
    {
      id: 3,
      albumName: "秋日",
      imgUrl: peaches,
      songList: [
        {
          id: 31,
          songName: "秋天的童话",
          singerName: "陈奕迅",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "秋日",
          imgUrl: peaches,
          duration: 200,
        },
        {
          id: 32,
          songName: "匆匆那年",
          singerName: "王菲",
          songUrl: "test1.ogg",
          isLike: false,
          albumName: "秋日",
          imgUrl: peaches,
          duration: 210,
        },
        {
          id: 33,
          songName: "岁月神偷",
          singerName: "金玟岐",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "秋日",
          imgUrl: peaches,
          duration: 220,
        },
        {
          id: 34,
          songName: "遥远的她",
          singerName: "张学友",
          songUrl: "test1.ogg",
          isLike: false,
          albumName: "秋日",
          imgUrl: peaches,
          duration: 240,
        },
      ],
    },
    {
      id: 4,
      albumName: "冬季",
      imgUrl: peaches,
      songList: [
        {
          id: 41,
          songName: "雪落下的声音",
          singerName: "李宗盛",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "冬季",
          imgUrl: peaches,
          duration: 190,
        },
        {
          id: 42,
          songName: "每当我想起你",
          singerName: "林宥嘉",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "冬季",
          imgUrl: peaches,
          duration: 195,
        },
        {
          id: 43,
          songName: "冬天的秘密",
          singerName: "周杰伦",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "冬季",
          imgUrl: peaches,
          duration: 205,
        },
        {
          id: 44,
          songName: "孤独的翅膀",
          singerName: "五月天",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "冬季",
          imgUrl: peaches,
          duration: 210,
        },
      ],
    },
    {
      id: 5,
      albumName: "春天",
      imgUrl: peaches,
      songList: [
        {
          id: 51,
          songName: "春风十里",
          singerName: "赵雷",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "春天",
          imgUrl: peaches,
          duration: 180,
        },
        {
          id: 52,
          songName: "花开时节",
          singerName: "林忆莲",
          songUrl: "test1.ogg",
          isLike: false,
          albumName: "春天",
          imgUrl: peaches,
          duration: 200,
        },
        {
          id: 53,
          songName: "小幸运",
          singerName: "田馥甄",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "春天",
          imgUrl: peaches,
          duration: 190,
        },
        {
          id: 54,
          songName: "在春天里",
          singerName: "李健",
          songUrl: "test1.ogg",
          isLike: false,
          albumName: "春天",
          imgUrl: peaches,
          duration: 210,
        },
      ],
    },
    {
      id: 6,
      albumName: "夏季",
      imgUrl: peaches,
      songList: [
        {
          id: 61,
          songName: "热带雨林",
          singerName: "蔡依林",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏季",
          imgUrl: peaches,
          duration: 180,
        },
        {
          id: 62,
          songName: "海边的故事",
          singerName: "李克勤",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏季",
          imgUrl: peaches,
          duration: 185,
        },
        {
          id: 63,
          songName: "阳光下的我们",
          singerName: "A-Lin",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏季",
          imgUrl: peaches,
          duration: 195,
        },
        {
          id: 64,
          songName: "清凉夏夜",
          singerName: "周华健",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "夏季",
          imgUrl: peaches,
          duration: 190,
        },
      ],
    },
    {
      id: 7,
      albumName: "怀旧",
      imgUrl: peaches,
      songList: [
        {
          id: 71,
          songName: "朋友",
          singerName: "周华健",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "怀旧",
          imgUrl: peaches,
          duration: 210,
        },
        {
          id: 72,
          songName: "明明白白我的心",
          singerName: "李宗盛",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "怀旧",
          imgUrl: peaches,
          duration: 215,
        },
        {
          id: 73,
          songName: "再见二丁目",
          singerName: "陈奕迅",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "怀旧",
          imgUrl: peaches,
          duration: 200,
        },
        {
          id: 74,
          songName: "童年",
          singerName: "罗大佑",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "怀旧",
          imgUrl: peaches,
          duration: 220,
        },
      ],
    },
    {
      id: 8,
      albumName: "经典",
      imgUrl: peaches,
      songList: [
        {
          id: 81,
          songName: "月亮代表我的心",
          singerName: "邓丽君",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "经典",
          imgUrl: peaches,
          duration: 230,
        },
        {
          id: 82,
          songName: "但愿人长久",
          singerName: "王菲",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "经典",
          imgUrl: peaches,
          duration: 240,
        },
        {
          id: 83,
          songName: "甜蜜蜜",
          singerName: "邓丽君",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "经典",
          imgUrl: peaches,
          duration: 250,
        },
        {
          id: 84,
          songName: "一剪梅",
          singerName: "费玉清",
          songUrl: "test.ogg",
          isLike: false,
          albumName: "经典",
          imgUrl: peaches,
          duration: 240,
        },
      ],
    },
  ]);

  return {
    mySongList,
  };
});
