/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./components/ContextMenu/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    IconEpPlus: typeof import('~icons/ep/plus')['default']
    List: typeof import('./components/Navbar/List/index.vue')['default']
    Logo: typeof import('./components/Logo/index.vue')['default']
    MusicProgressBar: typeof import('./components/MusicProgressBar/index.vue')['default']
    PlayImage: typeof import('./components/PlayImage/index.vue')['default']
    PlayList: typeof import('./components/PlayList/index.vue')['default']
    RollImages: typeof import('./components/RollImages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingPanel: typeof import('./components/SettingPanel/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    UserLogin: typeof import('./components/UserLogin/index.vue')['default']
  }
}
